---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: freecraft
  name: freecraft
  namespace: default
spec:
  selector:
    matchLabels:
      app: freecraft
  template:
    metadata:
      labels:
        app: freecraft
    spec:
      containers:
      - image: registry.gitlab.com/minetest/minetest/server:master
        name: freecraft
        ports:
        - containerPort: 30000
          protocol: UDP
        volumeMounts:
        - mountPath: /var/lib/freecraft
          name: freecraft-data
        - mountPath: /etc/freecraft
          name: config
      restartPolicy: Always
      volumes:
      - name: freecraft-data
        persistentVolumeClaim:
          claimName: freecraft-data
      - configMap:
          defaultMode: 420
          name: freecraft
        name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: freecraft
  name: freecraft
  namespace: default
spec:
  ports:
  - name: freecraft
    port: 30000
    protocol: UDP
  selector:
    app: freecraft
  type: NodePort
